services:
  - type: web
    name: bedelias-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_ENVIRONMENT
        value: production
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: bedelias-api.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: bedelias-db
          property: connectionString

databases:
  - name: bedelias-db
    plan: free
    databaseName: bedelias_api
    user: bedelias_user

